## @file
# Azure Pipeline build file for a build using ubuntu and GCC5.
#
# NOTE: This file is automatically synchronized from Mu DevOps. Update the original file there
#       instead of the file in this repo.
#
# - Mu DevOps Repo: https://github.com/microsoft/mu_devops
# - File Sync Settings: https://github.com/microsoft/mu_devops/blob/main/.sync/Files.yml
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

{% import '../../../Version.njk' as sync_version -%}

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: refs/tags/{{ sync_version.mu_devops }}

variables:
- group: architectures-arm-64-x86-64
- group: tool-chain-ubuntu-gcc

jobs:
- template: Jobs/PrGate.yml@mu_devops
  parameters:
    arch_list: $(arch_list)
    do_ci_build: true
    do_ci_setup: false
    extra_steps:
    - script: sudo apt-get install mingw-w64
      displayName: Install Windows Resource Compiler for Linux
    packages: SetupDataPkg
    target_list: DEBUG,RELEASE,NO-TARGET,NOOPT
    tool_chain_tag: $(tool_chain_tag)
    vm_image: $(vm_image)

- template: Jobs/Python/RunDevTests.yml@mu_devops
  parameters:
    code_cov_enabled: true
    custom_job_name: ubuntu
    root_package_folder: SetupDataPkg/Tools
    vm_image: $(vm_image)
