## @file
# Azure Pipeline build file for a build using Ubuntu and GCC.
#
# IMPORTANT: This file requires the local repo to contain a .azurepipelines/Matrix-Build-Job.yml file that
#            performs the actual build steps for the configurations and packages supported by the repo.
#
# NOTE: This file is automatically synchronized from Mu DevOps. Update the original file there
#       instead of the file in this repo.
#
# - Mu DevOps Repo: https://github.com/microsoft/mu_devops
# - File Sync Settings: https://github.com/microsoft/mu_devops/blob/main/.sync/Files.yml
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

{% import '../../Version.njk' as sync_version -%}

resources:
  repositories:
    - repository: mu_devops
      type: github
      endpoint: microsoft
      name: microsoft/mu_devops
      ref: refs/tags/{{ sync_version.mu_devops }}
  containers:
    - container: linux-gcc
      image: {{ sync_version.linux_build_container }}

variables:
- group: architectures-arm-64-x86-64
- group: tool-chain-ubuntu-gcc

jobs:
- template: Matrix-Build-Job.yml
  parameters:
    arch_list: $(arch_list)
    extra_build_args: CODE_COVERAGE=TRUE
    tool_chain_tag: 'GCC5'
    vm_image: $(vm_image)
    container_image: linux-gcc
    pool_name: $(pool_name)
    os_type: Linux
