# @file publish-release.yml
#
# A Github workflow that publishes all crates in a repository to crates.io and creates a release on
# GitHub.
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

name: Publish Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Release
    uses: microsoft/mu_devops/.github/workflows/ReleaseWorkflow.yml@main
    secrets:
      CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
    permissions:
      contents: write
      actions: read
      pull-requests: write
