# This workflow assists with initial triage of new issues by applying
# labels based on data provided in the issue.
#
# Configuration file that maps issue form input values to labels:
#   advanced-issue-labeler.yml
#
# Copyright (c) Microsoft Corporation.
# SPDX-License-Identifier: BSD-2-Clause-Patent
#
# For more information, see:
# https://github.com/stefanbuck/github-issue-parser
# https://github.com/redhat-plumbers-in-action/advanced-issue-labeler

name: Issue Triage Workflow

on:
  workflow_call:

jobs:
  triage_issues:
    name: Triage Issues
    runs-on: ubuntu-latest

    strategy:
      matrix:
        template: [ bug_report.yml, documentation_request.yml, feature_request.yml ]

    steps:
      - uses: actions/checkout@v3

      - name: Parse Issue Form
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/${{ matrix.template }}

      - name: Apply Labels from Triage
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          template: ${{ matrix.template }}
          token: ${{ secrets.GITHUB_TOKEN }}
